gettext("Logged in as");
gettext("Logout");
gettext("Overview");
gettext("Domains");
gettext("Records");
gettext("Templates");
gettext("User");
gettext("Supermasters");
gettext("Logged in as");
gettext("Overview");
gettext("Domains");
gettext("Records");
gettext("Templates");
gettext("User");
gettext("Supermasters");
gettext("Editing");
gettext("Edit userrights");
gettext("Edit domaintemplates");
gettext("New Entry");
gettext("Save");
gettext("New Entry");
gettext("Save");
gettext("Editing");
gettext("Type");
gettext("Content");
gettext("Priority");
gettext("Last change");
gettext("Action");
gettext("Type");
gettext("Action");
gettext("Nothing found");
gettext("Type");
gettext("Action");
gettext("Nothing found");
gettext("Do you really want to delete");
gettext("This can´t be undone!!");
gettext("Create new domain");
gettext("Search");
gettext("Save");
gettext("Save");
gettext("Do you really want to delete");
gettext("This can´t be undone!!");
gettext("Create new domain");
gettext("Search:");
gettext("Save");
gettext("Save");
gettext("Save");
gettext("Save");
gettext("Please login below");
gettext("Username");
gettext("Password");
gettext("Wrong username or password");
gettext("Login");
gettext("Please login below");
gettext("Username");
gettext("Password");
gettext("Last login:");
gettext("Last ip:");
gettext("Domaintype");
gettext("Recordtype");
gettext("Content");
gettext("Priority");
gettext("Last change");
gettext("Nothing found");
gettext("Domaintype");
gettext("Recordtype");
gettext("Content");
gettext("Priority");
gettext("Last change");
gettext("Fulltext search in ALL records");
gettext("Search");
gettext("Search");
gettext("Nameserver");
gettext("Account");
gettext("Action");
gettext("No supermasters found");
gettext("Manage supermasters");
gettext("New Entry");
gettext("Save");
gettext("Key");
gettext("Value");
gettext("Name");
gettext("Type");
gettext("Content");
gettext("Priority");
gettext("Action");
gettext("Name");
gettext("Type");
gettext("Content");
gettext("Prio");
gettext("Action");
gettext("New Record in Domain");
gettext("Save");
gettext("Default Records for new Domains");
gettext("You can use [DOMAIN] (mydomain.tld) and [STAMP] (2010061501) as a placeholder.");
gettext("New Entry");
gettext("Save");
gettext("Default Records for new Domains");
gettext("You can use [DOMAIN] (mydomain.tld) and [STAMP] (2010061501) as a placeholder.");
gettext("New Entry");
gettext("Save");
gettext("Username");
gettext("Admin");
gettext("New Domains");
gettext("Action");
gettext("No users found");
gettext("Username");
gettext("Password");
gettext("Admin");
gettext("Create new user");
gettext("Save");
gettext("The user has to relogin for changes to take effect!");
gettext("Username");
gettext("Password");
gettext("Admin");
gettext("Create new user");
gettext("The user has to relogin for changes to take effect!");
